pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh '''
                    ./gradlew clean install
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''
                    ./gradlew clean test
                '''
            }
        }
    }
}
