pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'nus-iss-backend'
        DOCKER_TAG = 'latest'
    }
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/urfrider/NUS-ISS-Designing-Modern-Software.git'
            }
        }

        stage('Build') {
            steps {
                sh '''
                cd ./backend
                chmod +x gradlew
                
                ./gradlew clean build
                '''
            }
        }

        stage('Create .env File') {
            steps {
                withCredentials([
                    string(credentialsId: 'DB_HOST', variable: 'DB_HOST'),
                    string(credentialsId: 'DB_USERNAME', variable: 'DB_USERNAME'),
                    string(credentialsId: 'DB_PASSWORD', variable: 'DB_PASSWORD')
                    string(credentialsId: 'SECRET_KEY', variable: 'SECRET_KEY')
                ]) {
                    sh '''
                    mkdir -p backend
                    echo "DB_HOST=$DB_HOST" > backend/.env
                    echo "DB_USERNAME=$DB_USERNAME" >> backend/.env
                    echo "DB_PASSWORD=$DB_PASSWORD" >> backend/.env
                    echo "SECRET_KEY=$SECRET_KEY" >> backend/.env
                    '''
                }
            }
        }

        stage('Test') {
            steps {
                withCredentials([
                    string(credentialsId: 'DB_HOST', variable: 'DB_HOST'),
                    string(credentialsId: 'DB_USERNAME', variable: 'DB_USERNAME'),
                    string(credentialsId: 'DB_PASSWORD', variable: 'DB_PASSWORD'),
                ]) {
                    echo "Testing the project..."
                    sh '''
                    cd ./backend
                    chmod +x gradlew
                    
                    ./gradlew clean test
                    '''
                }
            }
        }

        stage('Dockerize') {
            steps {
                script {
                    sh "docker build -t guokecheng/molymarket:backend-jenkins ./backend"
                    // sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ./backend"
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    // Stop & remove existing container if any
                    sh """
                    docker stop molymarket-backend || true
                    docker rm molymarket-backend || true
                    docker run -d --name molymarket-backend -p 8080:8080 guokecheng/molymarket:backend-jenkins
                    """
                    // sh """
                    // docker stop ${DOCKER_IMAGE} || true
                    // docker rm ${DOCKER_IMAGE} || true
                    // docker run -d --name ${DOCKER_IMAGE} -p 8080:8080 ${DOCKER_IMAGE}:${DOCKER_TAG}
                    // """
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
